### ISSUE TITLE
Usage of temporary tables

### ISSUE THREAD

**Issue by lancepioch** [redbastie/swift#3]
Not sure if this is possible, but this may dramatically speed up the command, especially when you have more than a handful of models being changed: https://github.com/redbastie/swift/blob/06aa0bb52a7236e2f8d41b02c465ba7e1612e7f3/src/Commands/MigrateAutoCommand.php#L29-L31

Blueprint instance has ->temporary() however it doesn't persist long enough for the table to compare the columns. If there's a way to persist it long enough for the whole command, then it would be an easy speed boost.

**Comment by redbastie** [comment]
It's a great idea, let me know if you figure out a way to persist it.
