### ISSUE TITLE
Middleware issue

### ISSUE THREAD

**Issue by happyclicker** [redbastie/swift#4]
Trying to use Spatie's permission package (https://spatie.be/docs/laravel-permission/v3/introduction) with yours, but I am not sure how to assign the middleware to routes in the Livewire components.  Is it possible to provide some documentation on using an extension like this, or, if necessary, provide a hook to call for middleware?

**Comment by redbastie** [comment]
You can apply a middleware string or array via the `$routeMiddleware` property in your component, e.g.:

	class Example extends SwiftComponent
	{
	    public $routeUri = '/example';
	    public $routeName = 'example';
	    public $routeMiddleware = 'auth';
	    ...

Via an array:

	class Example extends SwiftComponent
	{
	    public $routeUri = '/example';
	    public $routeName = 'example';
	    public $routeMiddleware = ['auth', 'can:view-example'];
	    ...

**Comment by happyclicker** [comment]
Ah!  Sorry about the dumb question, I missed adding the role: class to the
Kernel.php file.  Sigh.

I do have another question - I am trying to create components in sub
directories (LiveWire/Admin for example), but I can't seem to create them
with the crud command without getting errors, and moving them after they
are created (and updating the classes and doing the discover) doesn't work
either.

My application has a front end, and an admin area.  The front end is to
display data out of the model, and the admin area is for editing data.

**Comment by redbastie** [comment]
You can't create crud inside directories via the command at the moment. 

You can move the generated files into a directory after generating, just make sure to update the class namespaces and the route uri's.

**Comment by happyclicker** [comment]
Yes, this worked, I was hoping I wouldn't have to do that for each one,
but, well, it works.  :)

I do like your package, it is helping me get into using Livewire and I do
like the way you have the files laid out (and the model / DB stuff is
fantastic!)

An addition that would be helpful with the S:: functions would be a perms
check instead of having to use a closure.

Something like:
S::col(
S::perms('can:see-this',
S::button(S::icon('eye'))->title('Read')->link()->p(1)->click('$emit',
'showReadModal', $categories->id))),
...)

This would allow developers to have a lot more control over the nav bar,
buttons, data in views, etc without all the extra closure code.

**Comment by redbastie** [comment]
I like your idea of a method for permissions. 

I think I like S::can better than S::perms though.

**Comment by happyclicker** [comment]
Sure - that was just an example name I pulled out of the air.  :)

I noticed the package handles all the authentication except the forgot /
reset password page - was this an oversight?

**Comment by redbastie** [comment]
no, i was planning on adding forgot pw logic later, have just been too busy to get around to it.

**Comment by happyclicker** [comment]
Apologies for bothering you again, I am probably trying to use your library
for things that it wasn't intended, or I am just missing something basic in
the docs.

First, I don't see a hidden input field anywhere - but that may be moot
based on what I am trying to do.

My example: I have a product, and it needs images.  A product can have
multiple images, built into the relationship setup of the product model.

I list the products in the base scaffolding your tool creates, and I
figured out how to call the images page and bring up the images associated
with that product ID.  What I don't see is how to pass the product into the
create stub (without using a hidden field)?  Does this make sense?

**Comment by redbastie** [comment]
There are no hidden inputs. You shouldn't need hidden inputs as you can just use the `mount` method of the component to pre-populate with "hidden" data you want. Remember swift components are still fundamentally livewire components.

So to pass the product info to the component, check out the way the "update" components work with the CRUD generator command. When the modal is shown, it is passed an ID, and it pulls the model data in that way. You can do something similar for your images page. Actually, you probably want to pass the product ID via the url parameter/mount method.

So your product page component would have a `$routeUri` of something like `products/{product}`

Then, you would add a `mount` method in the component that would look something like this:

	class ProductPage extends SwiftComponent
	{
	    public $routeUri = '/products/{product}';
	    public $routeName = 'product-page';
	    public $pageTitle = 'Product Page';
	    public $product;

	    public function mount(Product $product)
	    {
	        $this->product = $product;
	    }

	    // ...

As you can see in this example, it uses route model binding, so it would automatically grab the product via the ID in the route uri.

**Comment by happyclicker** [comment]
Thank you again for your assistance, new to Livewire, as you can tell.  :)

I was working with the Select component, and it appears that it isn't using
the array index for the choice values, I believe the code
in Redbastie\Swift\Components\SelectComponent should be changed to:

public function options($options)
{
    $this->options = Arr::isAssoc($options) ? $options :
array_combine(array_keys($options), $options);

    return $this;
}

**Comment by redbastie** [comment]
It is that was by design. Think about it being like value => label. If it is not associative it will use the values for both the label and value.

**Comment by happyclicker** [comment]
Hmmmm

Passing in this variable did not use the integer values as the value= part
of the select box, it used the same for the label and value:

public $view_name = [
0 => 'Not Defined', 1 => 'Package', 2 => 'Item', 3 => 'Item Secondary', 4
=> 'Package Secondary', 5 => 'Item + Package', 6 => 'Label - Directions', 7
=> 'Label - Ingredients'
];

When I made that code change (to use array_keys), then it worked as
expected.

**Comment by redbastie** [comment]
That's because your array is still indexed even though you are manually setting the indexes.

You could bypass this by defining the indexes as string, e.g.:

	public $view_name = [
		'0' => 'Not Defined', 
		'1' => 'Package', 
		'2' => 'Item', 
		'3' => 'Item Secondary', 
		'4' => 'Package Secondary', 
		'5' => 'Item + Package', 
		'6' => 'Label - Directions', 
		'7' => 'Label - Ingredients'
	];

Notice how I've added quotation marks around the keys.

**Comment by happyclicker** [comment]
So that makes it difficult to deal with these types of settings in the
model that are commonly used to translate integer values into strings for
display purposes where the index is a value from an integer field in the
database.

Maybe I have been doing this wrong for a lot of years - do you have a trick
to handling this?  Does my proposed change break other implementations?

**Comment by redbastie** [comment]
You can grab those from the database directly and use the pluck method to put them into an array which can be used at the select options. 

E.g. MySetting::get()->pluck('name', 'id')->toArray()

**Comment by happyclicker** [comment]
I attempted this (without creating a new table for this data) in the way
you suggested, and it still doesn't give the correct value= in the select
box (should be the "id" value):

public $view_name = [
0 => 'Not Defined', 1 => 'Package', 2 => 'Item', 3 => 'Item Secondary', 4
=> 'Package Secondary', 5 => 'Item + Package', 6 => 'Label - Directions', 7
=> 'Label - Ingredients'
];

...

$arr = [];
foreach ($this->view_name as $id => $value) {
    $arr[] = ['id' => $id, 'name' => $value];
}
return (collect($arr)->pluck('name', 'id')->toArray());

**Comment by redbastie** [comment]
I'm looking into this.

**Comment by redbastie** [comment]
I just tested and its working fine.

I created a `Brand` model with `id` and `name`.

Then I created a `Vehicle` component with a `select` for the `brand_id`:

	S::select('brand_id')->options(Brand::all()->pluck('name', 'id')->toArray())->label('Brand')->modelDefer(),

The select was populated perfectly. The ID's were the option values, and the names were the option labels.

**Comment by happyclicker** [comment]
Is the id field an integer?

**Comment by redbastie** [comment]
Yes

**Comment by happyclicker** [comment]
Ah!  That was the needed clue.

So, it turns out if the first array key is a 0, then your function doesn't
work (because the key fields will always be an integer, causing your test
to fail).

It even works properly if I mix the order up (key 1 first, then key 0), so
this is my work-around.

I'm using Laravel 8.16.1 and PHP 7.4.5

**Comment by happyclicker** [comment]
If one edits the nav bar file and takes out the hook (// crud command
hook), when you execute

php artisan make:crud

it doesn't deal with it gracefully:

* ErrorException *


*  Undefined offset: 1*


  at vendor/redbastie/swift/src/Commands/MakeCrudCommand.php:31

     27▕ *            if (!**Str**::**contains**(**$navbarContents**, *
*$navItem**)) {*

     28▕                 *$hook **= *'// crud command hook'*;*

     29▕                 *preg_match**(*'/(.*)' *. **str_replace**(*'/'*, *
'\/'*, **$hook**) . *'/'*, **$navbarContents**, **$indent**);*

     30▕

*  ➜ ** 31*▕                 *$this**->**filesystem**->**put**(**$navbar**,
**str_replace**(**$hook**, **$navItem **. **PHP_EOL **. **$indent**[**1**]
. **$hook**, **$this**->**filesystem**->**get**(**$navbar**)));*

     32▕                 *$this**->**info**(*'Nav item inserted: ' *. *
*$navbar**);*

     33▕ *            }*

     34▕ *        }*

     35▕


      +14 vendor frames

  15  *artisan*:*37*

      Illuminate\Foundation\Console\Kernel::handle()
