### ISSUE TITLE
relationships how?

### ISSUE THREAD

**Issue by jvallef** [redbastie/swift#6]
Hi, this is an amazing product.

There is any other documentation? I will learn Laravel just to use your tool :-) for my personal projects. It's so fast build anything.

If models comes from those Livewire definitions, how do you set relationships?

How do you populate a select with brands from a different table?

Thanks

**Comment by jvallef** [comment]
Hi, found the solution in one of your answers...

S::select('brand_id')->options(Brand::all()->pluck('name', 'id')->toArray())->label('Brand')->modelDefer()

Was enough to find the solution. Thanks :-)

The remaining question if there is any other documentation I could check...

And a new one what approach do you suggest to upload images or files? I read also your comment about that, but can't figure how to do it.

Regards
J.

**Comment by redbastie** [comment]
Just the readme. Theres no elaborate documentation.

For uploading stuff - check the livewire docs for file uploads: https://laravel-livewire.com/docs/2.x/file-uploads

So you'd just create a S::file input and handle the file upload on `save` or whatever you prefer.

Swift components use Livewire under the hood, so the Livewire docs will help you a lot.
